var-1:
  var-1-1:
    var-1-1-1: "my-string-111"
    var-1-1-2: 112
    var-1-1-3: true
    var-1-1-4:
      var-1-1-4-1:
        var-1-1-4-1: "my-string-1141"
        var-1-1-4-2: 1142
        var-1-1-4-3: true
        var-1-1-4-4:
          var-1-1-4-4-1: false
  var-1-2: 12
var-2: "my-string-2"