name: 'YAML Outputs'
description: 'Read a YAML file, flatten it recursively into a set of output parameters'

inputs:
  file-path:
    required: true
    description: 'The path of the YAML file to read'

  separator:
    required: false
    description: 'The separator used to concatenate child properties. For example, "root__parent__child: true"'
    default: '__'

  export-env-variables:
    required: false
    description: 'Export outputs as environment variables'
    default: true

runs:
  using: 'node16'
  main: 'dist/index.js'
